name: CI Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: |
          npm install
          npm test

  # Security scan will be added once the app is deployed
  # security-scan:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: OWASP ZAP Security Scan
  #       uses: zaproxy/action-full-scan@v0.3.0
  #       with:
  #         target: 'http://your-app-url'  # Replace this once deployed
